/*
 * This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
 * http://creativecommons.org/licenses/by-sa/3.0/
 * Authors: Damian Lamers, Fernando van Loenhout
 */
package dlauncher.launcher;

import dlauncher.cache.CacheManager;
import dlauncher.cache.CacheStorage;
import dlauncher.cache.DefaultCacheManager;
import dlauncher.cache.MemoryCache;
import dlauncher.dialogs.Login;
import dlauncher.dialogs.TimeTingys;
import dlauncher.logger.Console;
import dlauncher.logger.TextAreaHandler;
import dlauncher.modpacks.ModpackGuiPanel;
import dlauncher.modpacks.ModpackManager;
import dlauncher.modpacks.download.DefaultDownloadLocation;
import dlauncher.modpacks.download.DlauncherModPackListing;
import dlauncher.modpacks.download.ModPackListingDownload;
import dlauncher.modpacks.download.ModPackListingVanilla;
import dlauncher.modpacks.packs.ModPack;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.Collection;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class Launcher extends javax.swing.JFrame {

    public String javaPath = System.getProperty("java.home");
    public File launcherPath = new File(".");
    private final CacheManager cache;
    private final Information information = new Information();
    private final Login login = new Login(this, true);
    private ModpackManager manager;

    /**
     * Creates new form Launcher
     */
    public Launcher() {
        initComponents();

        try {
            manager = new ModpackManager(
                    Arrays.<ModPackListingDownload>asList(
                            new ModPackListingVanilla(
                                    new URL("http://s3.amazonaws.com/Minecraft.Download/versions/versions.json")
                            ),
                            new DlauncherModPackListing(
                                    new URL("http://dlauncher.byethost13.com/api/modpack.json")
                            )
                    ),
                    cache = new DefaultCacheManager(
                            Arrays.<CacheStorage>asList(
                                    new MemoryCache(128, 1)
                            ),
                            Executors.newFixedThreadPool(4)
                    ),
                    new ModpackManager.ModPackListNoticer() {

                        @Override
                        public void modPackReady(Collection<? extends ModPack> newModPacks) {
                            for (ModPack modpack : newModPacks) {
                                Launcher.this.modPackContainer.add(new ModpackGuiPanel(modpack, cache));
                            }
                        }

                        @Override
                        public void modPackListingUpdated(int totalModPacks, ModPackListingDownload currentPage, ModPackListingDownload nextPage) {

                        }

                        @Override
                        public void allReady(Collection<ModPack> modpacks) {

                        }
                    });
        } catch (MalformedURLException ex) {
            throw new RuntimeException(ex);
        }
        manager.refreshModPackListing();
        try {
            setTitle("DLauncher  - " + information.getVersion());
            Logger.getGlobal().log(Level.INFO, "Loading News...");
            this.newsWebbrowser.setPage(information.getNewsLink());
            Logger.getGlobal().log(Level.INFO, "Succesfull!");
        } catch (IOException ex) {
            Logger.getGlobal().log(Level.WARNING, "FAILED:");
            Logger.getGlobal().log(Level.WARNING, "", ex);
        }

        TimeTingys timet = new TimeTingys(accountPasswordField);
        timet.setup();

        jTextField3.setText(javaPath);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        footer = new javax.swing.JPanel();
        footerLoginLabel = new javax.swing.JLabel();
        mainGui = new javax.swing.JTabbedPane();
        newsPane = new javax.swing.JPanel();
        newsScrollPane = new javax.swing.JScrollPane();
        newsWebbrowser = new javax.swing.JEditorPane();
        modPackPane = new javax.swing.JPanel();
        searchModPack = new javax.swing.JTextField();
        searchModPackGo = new javax.swing.JButton();
        modPackScrollPane = new javax.swing.JScrollPane();
        modPackContainer = new javax.swing.JPanel();
        accountPane = new javax.swing.JPanel();
        accountCenterPane = new javax.swing.JPanel();
        accountLoginLabel = new javax.swing.JLabel();
        accountUserNameLabel = new javax.swing.JLabel();
        accountUserNameField = new javax.swing.JTextField();
        accountPasswordLabel = new javax.swing.JLabel();
        accountPasswordField = new javax.swing.JPasswordField();
        accountLoginButton = new javax.swing.JButton();
        accountLogoutButton = new javax.swing.JButton();
        accountStayLogin = new javax.swing.JCheckBox();
        settingPane = new javax.swing.JTabbedPane();
        settingPaneMcJava = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        settingPaneTheme = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jFileChooser1.setBackground(new java.awt.Color(68, 69, 70));
        jFileChooser1.setDialogTitle("Select Java Path");
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.setName("JavaPathFileChooser"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DLauncher - OH NO SOMETHING WENT WRONG!");
        setForeground(java.awt.Color.lightGray);

        footer.setBackground(new java.awt.Color(45, 46, 49));

        footerLoginLabel.setForeground(new java.awt.Color(0, 204, 255));
        footerLoginLabel.setText("Please login in the Acount tab                                                                     ");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(footerLoginLabel)
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(footerLoginLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainGui.setBackground(new java.awt.Color(68, 69, 70));
        mainGui.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainGui.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainGui.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        mainGui.setOpaque(true);

        newsPane.setBackground(new java.awt.Color(102, 107, 111));

        newsWebbrowser.setEditable(false);
        newsWebbrowser.setText("ERROR:\n\nCan't connect to the site\n\n" + 
            "Sorry for the inconvenience");
        newsWebbrowser.setMargin(new java.awt.Insets(-11, -11, -11, -11));
        newsScrollPane.setViewportView(newsWebbrowser);

        javax.swing.GroupLayout newsPaneLayout = new javax.swing.GroupLayout(newsPane);
        newsPane.setLayout(newsPaneLayout);
        newsPaneLayout.setHorizontalGroup(
            newsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        newsPaneLayout.setVerticalGroup(
            newsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        mainGui.addTab("News", newsPane);

        modPackPane.setBackground(new java.awt.Color(102, 107, 111));

        searchModPack.setText("Search");
        searchModPack.setToolTipText("Search for a ModPack");

        searchModPackGo.setBackground(new java.awt.Color(133, 135, 139));
        searchModPackGo.setText("Go!");

        modPackScrollPane.setBackground(java.awt.Color.lightGray);
        modPackScrollPane.setAutoscrolls(true);
        modPackScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        modPackContainer.setBackground(java.awt.Color.gray);
        modPackContainer.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        modPackScrollPane.setViewportView(modPackContainer);

        javax.swing.GroupLayout modPackPaneLayout = new javax.swing.GroupLayout(modPackPane);
        modPackPane.setLayout(modPackPaneLayout);
        modPackPaneLayout.setHorizontalGroup(
            modPackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modPackPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchModPack, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchModPackGo)
                .addContainerGap(245, Short.MAX_VALUE))
            .addComponent(modPackScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        modPackPaneLayout.setVerticalGroup(
            modPackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modPackPaneLayout.createSequentialGroup()
                .addGroup(modPackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchModPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchModPackGo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modPackScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
        );

        mainGui.addTab("Packs", null, modPackPane, "Display The Arivable ModPack's");

        accountPane.setBackground(new java.awt.Color(102, 107, 111));
        accountPane.setLayout(new java.awt.GridBagLayout());

        accountCenterPane.setBackground(new java.awt.Color(102, 107, 111));

        accountLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLoginLabel.setText("Please log in with your premium minecraft account");

        accountUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountUserNameLabel.setText("E-Mail/username:");

        accountUserNameField.setBackground(new java.awt.Color(115, 112, 112));
        accountUserNameField.setForeground(new java.awt.Color(195, 192, 192));
        accountUserNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountUserNameFieldKeyTyped(evt);
            }
        });

        accountPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountPasswordLabel.setText("Password:");

        accountPasswordField.setBackground(new java.awt.Color(115, 112, 112));
        accountPasswordField.setForeground(new java.awt.Color(195, 192, 192));
        accountPasswordField.setEchoChar('?');
        accountPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountPasswordFieldKeyTyped(evt);
            }
        });

        accountLoginButton.setBackground(new java.awt.Color(133, 135, 139));
        accountLoginButton.setText("Login");
        accountLoginButton.setToolTipText("Click here to login");
        accountLoginButton.setEnabled(false);
        accountLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountLoginButtonActionPerformed(evt);
            }
        });

        accountLogoutButton.setBackground(new java.awt.Color(133, 135, 139));
        accountLogoutButton.setText("Logout");
        accountLogoutButton.setEnabled(false);

        accountStayLogin.setText("Stay logged in.");
        accountStayLogin.setEnabled(false);

        javax.swing.GroupLayout accountCenterPaneLayout = new javax.swing.GroupLayout(accountCenterPane);
        accountCenterPane.setLayout(accountCenterPaneLayout);
        accountCenterPaneLayout.setHorizontalGroup(
            accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCenterPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountCenterPaneLayout.createSequentialGroup()
                        .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountUserNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCenterPaneLayout.createSequentialGroup()
                                .addComponent(accountPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountUserNameField)
                            .addComponent(accountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(accountCenterPaneLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountLoginLabel)
                            .addGroup(accountCenterPaneLayout.createSequentialGroup()
                                .addComponent(accountLogoutButton)
                                .addGap(18, 18, 18)
                                .addComponent(accountStayLogin)
                                .addGap(18, 18, 18)
                                .addComponent(accountLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(92, 92, 92))
        );
        accountCenterPaneLayout.setVerticalGroup(
            accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCenterPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(accountLoginLabel)
                .addGap(18, 18, 18)
                .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountUserNameLabel))
                .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(accountCenterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLoginButton)
                    .addComponent(accountLogoutButton)
                    .addComponent(accountStayLogin))
                .addGap(31, 31, 31))
        );

        accountPane.add(accountCenterPane, new java.awt.GridBagConstraints());

        mainGui.addTab("Acount", accountPane);

        settingPane.setBackground(new java.awt.Color(102, 107, 111));
        settingPane.setOpaque(true);

        settingPaneMcJava.setBackground(java.awt.Color.gray);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Java Path:");

        jTextField3.setBackground(new java.awt.Color(115, 112, 112));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Java Path Unknow bug?                                           Browse -->");

        jButton3.setBackground(new java.awt.Color(133, 135, 139));
        jButton3.setText("...");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Java Parameters:");
        jLabel3.setToolTipText("Extera Java Command Line Parameters can be added here");

        jTextField4.setBackground(new java.awt.Color(115, 112, 112));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout settingPaneMcJavaLayout = new javax.swing.GroupLayout(settingPaneMcJava);
        settingPaneMcJava.setLayout(settingPaneMcJavaLayout);
        settingPaneMcJavaLayout.setHorizontalGroup(
            settingPaneMcJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPaneMcJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingPaneMcJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPaneMcJavaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(settingPaneMcJavaLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        settingPaneMcJavaLayout.setVerticalGroup(
            settingPaneMcJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPaneMcJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPaneMcJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingPaneMcJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        settingPane.addTab("Minecraft/Java", null, settingPaneMcJava, "Change the settings of Minecraft");

        settingPaneTheme.setBackground(java.awt.Color.gray);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select your theme!" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Theme:");
        jLabel7.setToolTipText("Set your faforite theme for this launcher!");

        jLabel8.setText("An Img that you cant see in Design");

        javax.swing.GroupLayout settingPaneThemeLayout = new javax.swing.GroupLayout(settingPaneTheme);
        settingPaneTheme.setLayout(settingPaneThemeLayout);
        settingPaneThemeLayout.setHorizontalGroup(
            settingPaneThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPaneThemeLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(settingPaneThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(settingPaneThemeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        settingPaneThemeLayout.setVerticalGroup(
            settingPaneThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPaneThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPaneThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(149, 149, 149)
                .addComponent(jLabel8)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        settingPane.addTab("tab2", settingPaneTheme);

        mainGui.addTab("Settings", settingPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainGui))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 383, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainGui)
                    .addGap(40, 40, 40)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   private void accountLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountLoginButtonActionPerformed
       //login button
       login.setVisible(true);

   }//GEN-LAST:event_accountLoginButtonActionPerformed

   private void accountUserNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountUserNameFieldKeyTyped
       if (accountUserNameField.getText().isEmpty()) {
           accountLoginButton.setEnabled(false);
       } else {
           if (accountPasswordField.getPassword().length != 0) {
               accountLoginButton.setEnabled(true);
           } else {
               accountLoginButton.setEnabled(false);
           }
       }
   }//GEN-LAST:event_accountUserNameFieldKeyTyped

   private void accountPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountPasswordFieldKeyTyped
       if (accountPasswordField.getPassword().length == 0) {
           accountLoginButton.setEnabled(false);
       } else {
           if (!(accountUserNameField.getText().isEmpty())) {
               accountLoginButton.setEnabled(true);
           } else {
               accountLoginButton.setEnabled(false);
           }
       }
   }//GEN-LAST:event_accountPasswordFieldKeyTyped

   private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       int returnVal = jFileChooser1.showOpenDialog(settingPaneMcJava);
       if (returnVal == JFileChooser.APPROVE_OPTION) {
           jTextField3.setText(jFileChooser1.getSelectedFile().getPath());
       }
   }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Console console = new Console();
                console.information.setIcon(console);
                console.setVisible(true);

                Logger.getGlobal().addHandler(new TextAreaHandler(console.jTextArea1, console));
                Logger.getLogger(Launcher.class.getName()).setUseParentHandlers(true);
                Logger.getLogger(Launcher.class.getName()).addHandler(new TextAreaHandler(console.jTextArea1, console));
                Logger.getGlobal().log(Level.INFO, "Started Logging..");

                Launcher launcher = new Launcher();

                Logger.getGlobal().log(Level.INFO, "Launcher visable: True");

                launcher.information.setIcon(launcher);
                launcher.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountCenterPane;
    private javax.swing.JButton accountLoginButton;
    private javax.swing.JLabel accountLoginLabel;
    private javax.swing.JButton accountLogoutButton;
    private javax.swing.JPanel accountPane;
    private static javax.swing.JPasswordField accountPasswordField;
    private javax.swing.JLabel accountPasswordLabel;
    private javax.swing.JCheckBox accountStayLogin;
    private javax.swing.JTextField accountUserNameField;
    private javax.swing.JLabel accountUserNameLabel;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel footerLoginLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTabbedPane mainGui;
    private javax.swing.JPanel modPackContainer;
    private static javax.swing.JPanel modPackPane;
    private javax.swing.JScrollPane modPackScrollPane;
    private javax.swing.JPanel newsPane;
    private javax.swing.JScrollPane newsScrollPane;
    private javax.swing.JEditorPane newsWebbrowser;
    private javax.swing.JTextField searchModPack;
    private javax.swing.JButton searchModPackGo;
    private javax.swing.JTabbedPane settingPane;
    private javax.swing.JPanel settingPaneMcJava;
    private javax.swing.JPanel settingPaneTheme;
    // End of variables declaration//GEN-END:variables
}
