/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dlauncher.launcher;

import dlauncher.dialogs.Login;
import dlauncher.dialogs.TimeTingys;
import dlauncher.logger.Console;
import dlauncher.logger.TextAreaHandler;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author damian
 */
public class Launcher extends javax.swing.JFrame {

   Information information = new Information();
   Login login = new Login(this,true);

   /**
    * Creates new form Launcher
    */
   public Launcher() {
      initComponents();
      
      try {
         setTitle("DLauncher  - " + information.getVersion());
         Logger.getGlobal().log(Level.INFO, "Connecting To New's-Page Site..");
         this.jEditorPane1.setPage(information.getNewsLink());
         Logger.getGlobal().log(Level.INFO, "Succesfull!");
      } catch (IOException ex) {
         Logger.getGlobal().log(Level.WARNING, "FAILED:");
         Logger.getGlobal().log(Level.WARNING, "", ex);
      }
      
      TimeTingys timet = new TimeTingys(jPasswordField1);
      timet.setup();

   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jTabbedPane1 = new javax.swing.JTabbedPane();
      jPanel4 = new javax.swing.JPanel();
      jScrollPane2 = new javax.swing.JScrollPane();
      jEditorPane1 = new javax.swing.JEditorPane();
      jPanel2 = new javax.swing.JPanel();
      jTextField1 = new javax.swing.JTextField();
      jButton2 = new javax.swing.JButton();
      jScrollPane3 = new javax.swing.JScrollPane();
      jPanel3 = new javax.swing.JPanel();
      Vanilla = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jPanel6 = new javax.swing.JPanel();
      jPanel5 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jTextField2 = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      jPasswordField1 = new javax.swing.JPasswordField();
      jButton6 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("DLauncher - OH NO SOMETHING WENT WRONG!");
      setForeground(java.awt.Color.lightGray);

      jPanel1.setBackground(new java.awt.Color(45, 46, 49));

      jLabel1.setForeground(new java.awt.Color(0, 204, 255));
      jLabel1.setText("Please login in the Acount tab                                                                     ");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(231, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(7, 7, 7)
            .addComponent(jLabel1)
            .addContainerGap(18, Short.MAX_VALUE))
      );

      jTabbedPane1.setBackground(new java.awt.Color(68, 69, 70));
      jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
      jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      jTabbedPane1.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
      jTabbedPane1.setOpaque(true);

      jPanel4.setBackground(new java.awt.Color(102, 107, 111));

      jEditorPane1.setEditable(false);
      jEditorPane1.setText("ERROR:\n\nCan't connect to the site\n\n" + 
         "Sorry for the inconvenience");
      jEditorPane1.setMargin(new java.awt.Insets(-11, -11, -11, -11));
      jScrollPane2.setViewportView(jEditorPane1);

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
      );

      jTabbedPane1.addTab("News", jPanel4);

      jPanel2.setBackground(new java.awt.Color(102, 107, 111));

      jTextField1.setText("Search");
      jTextField1.setToolTipText("Search for a ModPack");

      jButton2.setText("Go!");

      jScrollPane3.setBackground(java.awt.Color.lightGray);
      jScrollPane3.setAutoscrolls(true);
      jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);

      jPanel3.setBackground(java.awt.Color.gray);

      Vanilla.setInheritsPopupMenu(true);
      Vanilla.setOpaque(false);

      jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TEMP_Vanilla.png"))); // NOI18N

      jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("Minecraft Vanilla 1.7.2+");

      jButton3.setText("Add");

      jButton4.setText("Site");

      jButton5.setText("Donate to ModPack Author");

      javax.swing.GroupLayout VanillaLayout = new javax.swing.GroupLayout(Vanilla);
      Vanilla.setLayout(VanillaLayout);
      VanillaLayout.setHorizontalGroup(
         VanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(VanillaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(VanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(VanillaLayout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel2)
                  .addGap(0, 95, Short.MAX_VALUE))
               .addGroup(VanillaLayout.createSequentialGroup()
                  .addComponent(jButton3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButton5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton4)))
            .addContainerGap())
      );
      VanillaLayout.setVerticalGroup(
         VanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(VanillaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(VanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2)
               .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
            .addGroup(VanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton3)
               .addComponent(jButton4)
               .addComponent(jButton5))
            .addContainerGap())
      );

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(Vanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(Vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 466, Short.MAX_VALUE))
      );

      jScrollPane3.setViewportView(jPanel3);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
      );

      jTabbedPane1.addTab("Packs", null, jPanel2, "Display The Arivable ModPack's");

      jPanel6.setBackground(new java.awt.Color(102, 107, 111));
      jPanel6.setLayout(new java.awt.GridBagLayout());

      jPanel5.setBackground(new java.awt.Color(102, 107, 111));

      jLabel5.setForeground(new java.awt.Color(255, 255, 255));
      jLabel5.setText("Please log in with your premium minecraft account");

      jLabel4.setForeground(new java.awt.Color(255, 255, 255));
      jLabel4.setText("E-Mail/username:");

      jTextField2.setBackground(new java.awt.Color(115, 112, 112));
      jTextField2.setForeground(new java.awt.Color(195, 192, 192));

      jLabel6.setForeground(new java.awt.Color(255, 255, 255));
      jLabel6.setText("Password:");

      jPasswordField1.setBackground(new java.awt.Color(115, 112, 112));
      jPasswordField1.setForeground(new java.awt.Color(195, 192, 192));
      jPasswordField1.setEchoChar('?');

      jButton6.setBackground(new java.awt.Color(133, 135, 139));
      jButton6.setText("Login");
      jButton6.setToolTipText("Click here to login");
      jButton6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addGap(32, 35, Short.MAX_VALUE)
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                     .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)))
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addGap(0, 92, Short.MAX_VALUE)
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel5))))
            .addGap(91, 91, 91))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(59, 59, 59)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(91, 91, 91)
            .addComponent(jButton6)
            .addGap(104, 104, 104))
      );

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      jPanel6.add(jPanel5, gridBagConstraints);

      jTabbedPane1.addTab("Acount", jPanel6);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 383, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
               .addComponent(jTabbedPane1)
               .addGap(40, 40, 40)))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      //login button
      login.setVisible(true);
      
   }//GEN-LAST:event_jButton6ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
            Console console = new Console();
            console.information.setIcon(console);
            console.setVisible(true);

            Logger.getGlobal().addHandler(new TextAreaHandler(console.jTextArea1, console));
            Logger.getLogger(Launcher.class.getName()).setUseParentHandlers(true);
            Logger.getLogger(Launcher.class.getName()).addHandler(new TextAreaHandler(console.jTextArea1, console));
            Logger.getGlobal().log(Level.INFO, "Started Logging..");
            
            Launcher launcher = new Launcher();
            
            Logger.getGlobal().log(Level.INFO, "Launcher visable: True");
            
            launcher.information.setIcon(launcher);
            launcher.setVisible(true);
            
            
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel Vanilla;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JEditorPane jEditorPane1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private static javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private static javax.swing.JPasswordField jPasswordField1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   // End of variables declaration//GEN-END:variables
}
