/*
 * This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
 * http://creativecommons.org/licenses/by-sa/3.0/
 * Authors: Damian Lamers, Fernando van Loenhout
 */
package dlauncher.modpacks;

import dlauncher.cache.CacheManager;
import dlauncher.modpacks.packs.ModPack;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JOptionPane;

public class ModpackGuiPanel extends javax.swing.JPanel {

    public ModpackGuiPanel(ModPack modpack, CacheManager cache) {
        this();
        URL url;
        this.authorLabel.setText("Authors: " + modpack.getAuthors().toString());
        this.descriptionLabel.setText(modpack.getDescription());
        url = modpack.getDonateURL();
        if (url != null) {
            this.donateButton.setActionCommand(url.toString());
        } else {
            this.donateButton.setEnabled(false);
        }
        url = modpack.getWebsite();
        if (url != null) {
            this.websiteButton.setActionCommand(url.toString());
        } else {
            this.websiteButton.setEnabled(false);
        }
        cache.lazyLoadImageToLabel(modpack.getImage(), iconLabel, 64, 128, false);
    }
    
    public ModpackGuiPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      iconLabel = new javax.swing.JLabel();
      nameLabel = new javax.swing.JLabel();
      addButton = new javax.swing.JButton();
      descriptionLabel = new javax.swing.JLabel();
      donateButton = new javax.swing.JButton();
      websiteButton = new javax.swing.JButton();
      authorLabel = new javax.swing.JLabel();

      setBackground(java.awt.Color.gray);
      setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

      iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Unknow_Modpack_Image.png"))); // NOI18N

      nameLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
      nameLabel.setForeground(new java.awt.Color(255, 255, 255));
      nameLabel.setText("Unknow Modpack Title");

      addButton.setText("Add");

      descriptionLabel.setForeground(new java.awt.Color(241, 233, 233));
      descriptionLabel.setText("Unknow Modpack Description");
      descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

      donateButton.setText("Donate");
      donateButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            openAttachedURL(evt);
         }
      });

      websiteButton.setText("Site");
      websiteButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            openAttachedURL(evt);
         }
      });

      authorLabel.setForeground(new java.awt.Color(255, 255, 255));
      authorLabel.setText("Author:");
      authorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(addButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(donateButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(websiteButton))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                     .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(authorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(nameLabel)
                  .addGap(18, 18, 18)
                  .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(addButton)
               .addComponent(donateButton)
               .addComponent(websiteButton))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

    private void openAttachedURL(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAttachedURL
        if(evt.getActionCommand() != null) {
            try {
                URL url = new URL(evt.getActionCommand());
                Desktop.getDesktop().browse(url.toURI());
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(this, ex, "Unable to open URL", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_openAttachedURL


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addButton;
   private javax.swing.JLabel authorLabel;
   private javax.swing.JLabel descriptionLabel;
   private javax.swing.JButton donateButton;
   private javax.swing.JLabel iconLabel;
   private javax.swing.JLabel nameLabel;
   private javax.swing.JButton websiteButton;
   // End of variables declaration//GEN-END:variables
}
